openapi: 3.0.1
info:
  description: Esta API permite a administração de usuários
  title: API de Administração de Usuários
  version: 1.0.0
servers:
- url: /
tags:
- description: Operações administrativas
  name: Admin
paths:
  /usuarios/criar:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        description: Objeto de usuário a ser criado
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: Usuário criado com sucesso
        "400":
          content: {}
          description: Erro ao processar a requisição
      summary: Cria um novo usuário
      tags:
      - Admin
      x-codegen-request-body-name: usuario
      x-content-type: application/json
      x-accepts: application/json
  /usuarios/todos:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Usuario'
                type: array
          description: Lista de usuários
        "400":
          content: {}
          description: Erro ao processar a requisição
      summary: Obtém todos os usuários
      tags:
      - Admin
      x-accepts: application/json
  /usuarios/cpf/{cpf}:
    get:
      parameters:
      - description: CPF do usuário a ser buscado
        in: path
        name: cpf
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: Usuário encontrado
        "404":
          content: {}
          description: Usuário não encontrado
      summary: Obtém um usuário por CPF
      tags:
      - Admin
      x-accepts: application/json
  /usuarios/atualizar/{cpf}:
    put:
      parameters:
      - description: CPF do usuário a ser atualizado
        in: path
        name: cpf
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        description: Objeto de usuário atualizado
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: Usuário atualizado com sucesso
        "404":
          content: {}
          description: Usuário não encontrado
        "400":
          content: {}
          description: Erro ao processar a requisição
      summary: Atualiza um usuário por CPF
      tags:
      - Admin
      x-codegen-request-body-name: usuario
      x-content-type: application/json
      x-accepts: application/json
  /usuarios/excluir/{cpf}:
    delete:
      parameters:
      - description: CPF do usuário a ser excluído
        in: path
        name: cpf
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: Usuário excluído com sucesso
        "404":
          content: {}
          description: Usuário não encontrado
      summary: Exclui um usuário por CPF
      tags:
      - Admin
      x-accepts: application/json
components:
  schemas:
    Usuario:
      example:
        cpf: cpf
        nome: nome
        id: 0
        email: email
      properties:
        id:
          type: integer
        nome:
          type: string
        cpf:
          type: string
        email:
          type: string
      type: object
x-original-swagger-version: "2.0"

