pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Faz o checkout do código fonte principal
                git url: 'https://github.com/leandrofuenge/Projeto-Bicicletario-Sistema.git', branch: 'main'
            }
        }

        stage('Build and Test') {
            steps {
                // Debug: imprimir o diretório atual
                sh 'pwd'

                // Debug: listar os arquivos no diretório atual
                sh 'ls -la'

                // Executa o build usando Maven
                dir('BiciAutenteBackEnd/bici') {
                      // Debug: imprimir o diretório atual
                    sh 'pwd'

                    // Debug: listar os arquivos no diretório atual
                    sh 'ls -la'

                    sh 'echo "Hello, Jenkins!"'


                    sh 'mvn clean compile'
                }
            }
        }
    }

    post {
        success {
            echo 'Build e testes concluídos com sucesso!'
        }
        failure {
            echo 'Ocorreu um erro durante a build ou testes.'
        }
    }
}
